apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensse-tracker

  labels:
    app: expensse-tracker

spec:
  replicas: 3
  selector:
    matchLabels:
      app: expensse-tracker

  template:
    metadata:
      labels:
        app: expensse-tracker

    spec:
      containers:
      - name: expensse-tracker

        image: monregistre.dockerhub.com/expensse-tracker:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

