
apiVersion: v1
kind: Service
metadata:
  name: my-srv
  labels:
    app: expensse-tracker

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: expensse-tracker

